Vname: Build & Deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key

        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Create SSH key
        run: |
          ssh -i $SSH_KEY_PATH root@77.222.60.23
          cd /var/www/frontend
          npm run build
          pm2 delete 0
          pm2 serve dist 80
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key      
        
