name: Build & Deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "77.222.60.23"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/frontend
            npm run build
            pm2 delete 0
            pm2 serve dist 3000
            pm2 save

        
